### ISSUE TITLE
Consider using `phpDocumentor/Reflection` dependency

### ISSUE THREAD

**Issue by arogachev** [yiisoft/proxy#31]
Maybe it can help to write less code (especially with configs and `ClassConfigFactory`), but maybe will bring unnecessary complexity and abstraction. Need to check the real benefits.

This dependency is used in yii2-apidoc by the way.

**Comment by samdark** [comment]
Do we rely on phpdoc in the package?

**Comment by arogachev** [comment]
@samdark Nope.

**Comment by samdark** [comment]
Why would phpDocumentor/Reflection be useful then?

**Comment by arogachev** [comment]
Seems like at least for configs. But let's close it for now until I have more concrete examples / suggestions.
